name: Pronto
on: [pull_request]

jobs:
  pronto:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: gem install pronto pronto-rubocop rubocop-rspec rubocop-performance rubocop-rails pronto-flay pronto-reek pronto-fasterer pronto-rails_best_practices pronto-brakeman
      - run: git fetch
      - run: PRONTO_PULL_REQUEST_ID="$(jq --raw-output .number "$GITHUB_EVENT_PATH")" PRONTO_GITHUB_ACCESS_TOKEN="${{ secrets.PRONTO_GITHUB_TOKEN }}" pronto run -f github_status github_pr -c origin/master
